version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - pizza_shop_db_data:/bitnami/postgresql

volumes:
  pizza_shop_db_data:
